In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [53]:
# Applying LDA
def LDA(indep_X,dep_Y,n):
    from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
    lda = LDA(n_components = 5)
    X_train = lda.fit_transform(indep_X,dep_Y)
    X_test = lda.transform(indep_X)
    return X_test

In [54]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
def cm_prediction(classifier,X_test):
        y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
        from sklearn.metrics import confusion_matrix
        cm = confusion_matrix(y_test, y_pred)
        
        from sklearn.metrics import accuracy_score 
        from sklearn.metrics import classification_report 
            #from sklearn.metrics import confusion_matrix
            #cm = confusion_matrix(y_test, y_pred)

        Accuracy=accuracy_score(y_test, y_pred )

        report=classification_report(y_test, y_pred)
        return  classifier,Accuracy,report,X_test,y_test,cm

def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm

In [55]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['LDA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [56]:
dataset1=pd.read_csv("prep.csv",index_col=None)

df2=dataset1

df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes', 1)
dep_Y=df2['classification_yes']

df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [57]:
LDA=Lda(indep_X,dep_Y,5)
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]
LDA

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(27, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)

array([[-0.81981835],
       [-1.56847644],
       [ 0.52064042],
       [-1.93238122],
       [-0.79282681],
       [-1.82662484],
       [ 0.11256948],
       [ 1.01518225],
       [ 0.39830217],
       [ 0.99480451],
       [-0.16703827],
       [-1.05291541],
       [ 2.06936146],
       [-1.30691042],
       [-1.0161603 ],
       [ 3.0185253 ],
       [ 0.33846521],
       [-0.71157414],
       [ 2.49260119],
       [ 0.60269757],
       [ 1.49255882],
       [ 2.28295831],
       [ 1.69137383],
       [-0.35645975],
       [-1.90723877],
       [ 2.1471307 ],
       [ 3.30618975],
       [ 2.25928344],
       [ 2.8327288 ],
       [ 2.03335993],
       [-1.71000954],
       [ 2.93691686],
       [ 2.55074692],
       [ 1.11305331],
       [ 2.45881865],
       [ 1.79014666],
       [ 1.42410924],
       [ 0.05456152],
       [ 0.92287816],
       [ 1.15772315],
       [ 3.69356759],
       [ 1.80061365],
       [ 2.50764912],
       [ 1.63941818],
       [-0.68242445],
       [ 1.51497615],
       [ 2.02208412],
       [ 2.37023552],
       [ 0.81088436],
       [ 2.1503289 ],
       [ 2.62474253],
       [-2.11852443],
       [ 2.41949888],
       [ 2.49452978],
       [-1.000105  ],
       [ 3.30212941],
       [ 1.81022106],
       [ 2.48823466],
       [ 2.2971062 ],
       [ 2.33222799],
       [-1.40365193],
       [-0.8475226 ],
       [ 0.63483069],
       [ 0.82403349],
       [-1.0887866 ],
       [ 2.18137575],
       [ 1.49705389],
       [ 2.62150898],
       [ 3.41997495],
       [-2.45024297],
       [-1.86032453],
       [ 2.15167477],
       [ 2.00340499],
       [ 2.71509092],
       [ 2.63238311],
       [-0.62439901],
       [ 2.81551766],
       [-0.47592591],
       [ 3.10263019],
       [ 2.03772426],
       [ 0.24812207],
       [ 1.65861909],
       [ 1.53324126],
       [-1.63702612],
       [ 1.87248066],
       [ 2.64121114],
       [ 1.75545819],
       [-2.40223462],
       [-2.88666277],
       [ 2.13628647],
       [ 0.90645276],
       [-1.26574357],
       [-1.19105959],
       [ 2.43286084],
       [ 2.24266439],
       [ 3.29539456],
       [-2.1893708 ],
       [ 0.22784199],
       [ 1.44643354],
       [ 1.6016432 ],
       [ 2.41453477],
       [ 3.30369614],
       [ 0.08946481],
       [ 2.25573589],
       [ 2.65257561],
       [ 0.86778281],
       [ 3.49368661],
       [ 2.19611023],
       [ 0.07318176],
       [ 2.0804533 ],
       [ 3.260783  ],
       [ 2.08310368],
       [ 2.50782779],
       [ 2.16363677],
       [-0.66001142],
       [-0.32809644],
       [-2.41001675],
       [-0.87743521],
       [-2.56931287],
       [ 0.41775   ],
       [-1.34979394],
       [ 2.91324377],
       [ 2.11797248],
       [ 1.88961546],
       [-1.50268268],
       [-2.15577209],
       [-2.66492384],
       [-1.33387224],
       [-2.30259948],
       [-0.99706535],
       [ 2.85661527],
       [ 1.30574177],
       [ 3.2529924 ],
       [-0.73248709],
       [ 0.12768633],
       [-1.96877806],
       [ 0.00773866],
       [-2.10170074],
       [ 0.95254071],
       [ 1.441574  ],
       [ 2.47170872],
       [ 1.42423133],
       [ 2.07873024],
       [ 1.35004965],
       [-1.54418939],
       [ 0.56390723],
       [-1.17397961],
       [-1.55691762],
       [-1.91213564],
       [-1.34472324],
       [-2.06754386],
       [-2.43676717],
       [ 2.15040938],
       [ 1.86982964],
       [ 3.27761169],
       [-3.60099386],
       [ 2.34518911],
       [-2.64692499],
       [ 0.69029596],
       [-2.62050163],
       [-2.0404229 ],
       [-1.71026379],
       [-1.03555987],
       [ 0.39944582],
       [-1.91838066],
       [-1.02921583],
       [ 1.67389141],
       [ 2.02450243],
       [ 1.38539403],
       [-1.00755678],
       [-0.95336531],
       [ 2.05689201],
       [ 2.48087419],
       [ 2.03134408],
       [-2.26839727],
       [-3.54777437],
       [ 2.16247533],
       [ 2.02319752],
       [ 2.58131166],
       [-1.50553552],
       [-1.1659806 ],
       [-1.25690765],
       [-1.41009565],
       [ 2.88812101],
       [-3.45769206],
       [-1.93552329],
       [-3.25313526],
       [-0.12106633],
       [ 0.24514451],
       [ 0.79551737],
       [-2.55627088],
       [-0.98359747],
       [ 1.38676485],
       [ 2.0903679 ],
       [-1.30793645],
       [-0.51425705],
       [-2.64459316],
       [-1.4414813 ],
       [-3.47010214],
       [-2.14887402],
       [ 1.83397263],
       [ 1.04669212],
       [ 2.7104749 ],
       [ 2.59082548],
       [ 2.55228859],
       [ 2.1458687 ],
       [-2.64200585],
       [-1.83297973],
       [-0.46535019],
       [-0.2197781 ],
       [-1.78334414],
       [-3.19944622],
       [-4.52197225],
       [ 2.266096  ],
       [ 2.88471185],
       [ 2.23079434],
       [-2.79434364],
       [-1.70241824],
       [-2.15550058],
       [-1.29610584],
       [ 2.55677071],
       [ 2.33036859],
       [ 1.85498631],
       [ 1.89167819],
       [-2.61700594],
       [ 1.84101362],
       [ 1.80826345],
       [ 3.12834473],
       [ 2.85062376],
       [-1.71242729],
       [-2.66779957],
       [-2.99501986],
       [-0.77608768],
       [-2.44351198],
       [-3.74754642],
       [-2.50921677],
       [-1.93360354],
       [ 2.14608179],
       [ 2.10348106],
       [-2.2261995 ],
       [ 0.30930259],
       [-3.11252783],
       [-1.14766958],
       [-2.74755953],
       [-1.71008247],
       [-0.48302338],
       [-1.48383296],
       [-3.15917799],
       [ 0.4923493 ],
       [-1.31949194],
       [-0.40566187],
       [-2.65516971],
       [ 0.44147271],
       [-0.90451457],
       [ 2.12254048],
       [ 2.15793145],
       [ 1.66182763],
       [ 2.47383791],
       [-3.39505823],
       [ 0.1832877 ],
       [-2.54096066],
       [-1.1131611 ],
       [-1.05720706],
       [ 0.40743264],
       [-0.05800392],
       [ 3.3568129 ],
       [ 2.12444228],
       [-2.52589811],
       [-1.48890532],
       [-1.28417247],
       [-1.17994842],
       [ 0.34197075],
       [-1.71571643],
       [-1.39095907],
       [ 0.49507486],
       [ 2.71762779],
       [ 3.13949743],
       [-3.33722216],
       [-0.78268044],
       [-1.00797056],
       [-1.1685915 ],
       [-1.23819813],
       [ 2.07507546],
       [ 2.43050754],
       [-2.25238895],
       [-3.30561949],
       [-1.20363886],
       [-0.40325448],
       [-3.79029308],
       [-2.30025379],
       [ 1.79241397],
       [ 1.63229547],
       [-1.0807542 ],
       [-0.89439048],
       [-1.24034961],
       [-2.95727186],
       [-0.23650065],
       [-2.80742376],
       [-2.20358904],
       [-0.61114237],
       [-2.56160538],
       [-0.88390748],
       [-2.53691842],
       [-2.95906228],
       [-2.00009287],
       [-1.14878995],
       [-2.66755066],
       [ 1.64573938],
       [ 2.7958337 ],
       [-0.92638986],
       [-2.44580529],
       [-0.61480658],
       [ 2.20427437],
       [ 1.93709863],
       [ 0.43422252],
       [ 0.26869031],
       [-0.73547904],
       [-1.93821168],
       [-2.69530443],
       [-0.40067562],
       [ 3.43434073],
       [-1.13706838],
       [-3.32212882],
       [-0.95929904],
       [-4.02828632],
       [ 0.09521934],
       [-0.65988541],
       [-3.15939515],
       [ 3.53132807],
       [-1.56146322],
       [-0.09915253],
       [-0.29086058],
       [-0.83289613],
       [-2.2586995 ],
       [ 2.38299318],
       [-0.67291669],
       [-0.49231589],
       [-2.5806123 ],
       [-1.96197077],
       [-2.13717244],
       [-1.39626585],
       [-2.20171743],
       [ 2.30763913],
       [ 2.02919432],
       [-1.98723352],
       [-0.82399509],
       [-2.77118436],
       [-1.30348252],
       [-1.69928808],
       [ 1.8547829 ],
       [ 2.69393335],
       [ 3.28371462],
       [-1.159746  ],
       [ 0.54631957],
       [-1.09800896],
       [ 0.65199569],
       [-0.63251627],
       [-0.77909483],
       [ 2.06731352],
       [-1.89873342],
       [-2.54759177],
       [-0.92413364],
       [-3.25194878],
       [-0.34980293],
       [-1.7384897 ],
       [ 2.0872066 ],
       [ 2.37273476],
       [-2.10560562],
       [ 0.09632953],
       [ 2.93817125],
       [-2.46102539],
       [ 0.55023477],
       [ 0.12269198],
       [ 1.72608013],
       [ 1.12249609],
       [-1.99358444],
       [-2.32881831],
       [ 0.05094879],
       [-1.71501979],
       [-0.97732097],
       [-0.64376818],
       [ 3.0660933 ],
       [-1.52999615],
       [-2.02890021],
       [ 2.05056829],
       [ 2.33488068],
       [-0.9698439 ],
       [-1.42259305],
       [-1.54254311],
       [ 0.275876  ],
       [ 0.23114975],
       [-3.84407814],
       [-1.5842342 ],
       [-1.39111965],
       [ 0.59759196],
       [-2.38837037],
       [-3.14842633],
       [-1.26352395],
       [ 2.32625144]])

In [58]:
X_train, X_test, y_train, y_test=split_scalar(LDA,dep_Y)   
    
        
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):
C:\Users\spavi\Anaconda3\Anaconda\envs\aiml\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [34]:
#2
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
LDA     0.99  0.98  0.98  0.98  0.98     0.99   0.99

In [35]:
#3
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
LDA     0.99  0.98  0.98  0.98  0.98     0.99   0.99

In [26]:
#4
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
LDA     0.99  0.98  0.98  0.98  0.98     0.99   0.99

In [59]:
#5
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
LDA     0.99  0.98  0.98  0.98  0.98     0.99   0.99